# Generated by Django 5.1.1 on 2024-09-11 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotLog',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(help_text='The unique identifier for this record', max_length=255, primary_key=True, serialize=False)),
                ('platform', models.IntegerField(db_index=True, help_text='The platform this record belongs to')),
                ('object_id', models.CharField(help_text='The id of the object this record belongs to', max_length=255)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='The user who logged this record', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Log',
                'verbose_name_plural': 'Pilot Logs',
            },
        ),
    ]
