# Generated by Django 5.1.1 on 2024-09-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True)),
                ('aircraft_code', models.CharField(help_text='Unique identifier for the aircraft', max_length=255, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False, help_text='Indicates if the aircraft is currently active')),
                ('aerobatic', models.BooleanField(default=False, help_text='Indicates if the aircraft is capable of aerobatic maneuvers')),
                ('category', models.IntegerField(help_text='Category of the aircraft')),
                ('aircraft_class', models.IntegerField(help_text='Class of the aircraft')),
                ('company', models.CharField(help_text='Company or manufacturer of the aircraft', max_length=255)),
                ('complex', models.BooleanField(default=False, help_text='Indicates if the aircraft is classified as complex')),
                ('cond_log', models.IntegerField(help_text='Condition log number')),
                ('default_app', models.IntegerField(help_text='Default approach setting')),
                ('default_launch', models.IntegerField(help_text='Default launch setting')),
                ('default_log', models.IntegerField(help_text='Default log setting')),
                ('default_ops', models.IntegerField(help_text='Default operations setting')),
                ('device_code', models.IntegerField(help_text='Code for the device associated with the aircraft')),
                ('efis', models.BooleanField(default=False, help_text='Indicates if the aircraft has Electronic Flight Instrument System')),
                ('f_n_p_t', models.IntegerField(default=0, help_text='Flight and Navigation Procedures Trainer level')),
                ('fav_list', models.BooleanField(default=False, help_text='Indicates if the aircraft is in the favorite list')),
                ('fin', models.CharField(blank=True, help_text='Financial or other identifier', max_length=255)),
                ('high_perf', models.BooleanField(default=False, help_text='Indicates if the aircraft is classified as high performance')),
                ('kg5700', models.BooleanField(default=False, help_text='Indicates if the aircraft is over 5700 kg')),
                ('make', models.CharField(help_text='Make of the aircraft', max_length=255)),
                ('model', models.CharField(help_text='Model of the aircraft', max_length=255)),
                ('power', models.IntegerField(default=1, help_text='Power rating of the aircraft')),
                ('rating', models.CharField(blank=True, help_text='Rating of the aircraft', max_length=255)),
                ('ref_search', models.CharField(help_text='Reference for search purposes', max_length=255)),
                ('reference', models.CharField(help_text='Reference identifier for the aircraft', max_length=255)),
                ('run2', models.BooleanField(default=False, help_text='Indicates if the aircraft has a second engine or run capability')),
                ('sea', models.BooleanField(default=False, help_text='Indicates if the aircraft is sea-capable')),
                ('seats', models.IntegerField(help_text='Number of seats in the aircraft')),
                ('sub_model', models.CharField(blank=True, help_text='Sub-model of the aircraft', max_length=255)),
                ('t_m_g', models.BooleanField(default=False, help_text='Indicates if the aircraft is a Touring Motor Glider')),
                ('tail_wheel', models.BooleanField(default=False, help_text='Indicates if the aircraft has a tailwheel configuration')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
            },
        ),
    ]
