# Generated by Django 5.1.1 on 2024-09-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0005_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePic',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True, help_text='Date and time of last modification to record', verbose_name='RecordModified')),
                ('img_code', models.CharField(help_text='Unique identifier for the image', max_length=255, primary_key=True, serialize=False, verbose_name='ImgCode')),
                ('file_ext', models.CharField(help_text='File extension of the image', max_length=10, verbose_name='FileExt')),
                ('file_name', models.CharField(help_text='Name of the image file', max_length=255, verbose_name='FileName')),
                ('img_download', models.BooleanField(default=False, help_text='Indicates if the image has been downloaded', verbose_name='Img_Download')),
                ('img_upload', models.BooleanField(default=False, help_text='Indicates if the image has been uploaded', verbose_name='Img_Upload')),
                ('link_code', models.CharField(help_text='Code linking the image to other records', max_length=255, verbose_name='LinkCode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
