# Generated by Django 5.1.1 on 2024-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0006_imagepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitRules',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True, help_text='Date and time of last modification to record', verbose_name='RecordModified')),
                ('limit_code', models.CharField(help_text='Unique identifier for the limit rule', max_length=36, primary_key=True, serialize=False, verbose_name='LimitCode')),
                ('l_from', models.DateField(help_text='Start date of the limit rule', verbose_name='LFrom')),
                ('l_minutes', models.IntegerField(help_text='Number of minutes for the limit rule', verbose_name='LMinutes')),
                ('l_period_code', models.IntegerField(help_text='Code representing the period for the limit rule', verbose_name='LPeriodCode')),
                ('l_to', models.DateField(help_text='End date of the limit rule', verbose_name='LTo')),
                ('l_type', models.IntegerField(help_text='Type of the limit rule', verbose_name='LType')),
                ('l_zone', models.IntegerField(help_text='Zone associated with the limit rule', verbose_name='LZone')),
            ],
            options={
                'verbose_name': 'Limit Rule',
                'verbose_name_plural': 'Limit Rules',
            },
        ),
    ]
