# Generated by Django 5.1.1 on 2024-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0007_limitrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQuery',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True, help_text='Date and time of last modification to record', verbose_name='RecordModified')),
                ('mq_code', models.CharField(help_text='Unique identifier for the query', max_length=36, primary_key=True, serialize=False, verbose_name='mQCode')),
                ('name', models.CharField(help_text='Name of the query, e.g., TIME: Actual Instrument', max_length=255, verbose_name='Name')),
                ('quick_view', models.BooleanField(default=False, help_text='Indicates if the query is available in quick view', verbose_name='QuickView')),
                ('short_name', models.CharField(blank=True, help_text='Short name or abbreviation for the query', max_length=255, verbose_name='ShortName')),
            ],
            options={
                'verbose_name': 'My Query',
                'verbose_name_plural': 'My Queries',
            },
        ),
    ]
