# Generated by Django 5.1.1 on 2024-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0008_myquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQueryBuild',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True, help_text='Date and time of last modification to record', verbose_name='RecordModified')),
                ('mqb_code', models.CharField(help_text='Unique identifier for the query build', max_length=36, primary_key=True, serialize=False, verbose_name='mQBCode')),
                ('build1', models.CharField(help_text='First build parameter', max_length=255, verbose_name='Build1')),
                ('build2', models.IntegerField(help_text='Second build parameter', verbose_name='Build2')),
                ('build3', models.IntegerField(help_text='Third build parameter', verbose_name='Build3')),
                ('build4', models.CharField(help_text='Fourth build parameter', max_length=255, verbose_name='Build4')),
                ('mq_code', models.CharField(help_text='Associated query code', max_length=36, verbose_name='mQCode')),
            ],
            options={
                'verbose_name': 'My Query Build',
                'verbose_name_plural': 'My Query Builds',
            },
        ),
        migrations.AlterModelOptions(
            name='airfield',
            options={'verbose_name': 'Airfield', 'verbose_name_plural': 'Airfields'},
        ),
        migrations.AlterModelOptions(
            name='imagepic',
            options={'verbose_name': 'ImagePic', 'verbose_name_plural': 'ImagePics'},
        ),
    ]
