# Generated by Django 5.1.1 on 2024-09-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0009_myquerybuild_alter_airfield_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True, help_text='Date and time of last modification to record', verbose_name='RecordModified')),
                ('pilot_code', models.CharField(help_text='Unique identifier for the pilot', max_length=36, primary_key=True, serialize=False, verbose_name='PilotCode')),
                ('active', models.BooleanField(default=True, help_text='Indicates if the pilot is currently active', verbose_name='Active')),
                ('certificate', models.CharField(blank=True, help_text="Pilot's certificate information", max_length=255, verbose_name='Certificate')),
                ('company', models.CharField(help_text='Company or airline the pilot works for', max_length=255, verbose_name='Company')),
                ('facebook', models.URLField(blank=True, help_text="Pilot's Facebook profile URL", verbose_name='Facebook')),
                ('fav_list', models.BooleanField(default=False, help_text='Indicates if the pilot is in the favorite list', verbose_name='FavList')),
                ('linkedin', models.URLField(blank=True, help_text="Pilot's LinkedIn profile URL", verbose_name='LinkedIn')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the pilot', verbose_name='Notes')),
                ('phone_search', models.CharField(blank=True, help_text='Phone number search field', max_length=255, verbose_name='PhoneSearch')),
                ('pilot_email', models.EmailField(blank=True, help_text="Pilot's email address", max_length=254, verbose_name='PilotEMail')),
                ('pilot_name', models.CharField(help_text='Full name of the pilot', max_length=255, verbose_name='PilotName')),
                ('pilot_phone', models.CharField(blank=True, help_text="Pilot's phone number", max_length=255, verbose_name='PilotPhone')),
                ('pilot_ref', models.CharField(help_text='Reference number for the pilot', max_length=255, verbose_name='PilotRef')),
                ('pilot_search', models.CharField(help_text='Search field for the pilot', max_length=255, verbose_name='PilotSearch')),
                ('roster_alias', models.CharField(blank=True, help_text='Alias used for roster purposes', max_length=255, verbose_name='RosterAlias')),
                ('user_api', models.CharField(blank=True, help_text='API user identifier for the pilot', max_length=255, verbose_name='UserAPI')),
            ],
            options={
                'verbose_name': 'Pilot',
                'verbose_name_plural': 'Pilots',
            },
        ),
    ]
