# Generated by Django 5.1.1 on 2024-09-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0010_pilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('record_modified', models.DateTimeField(auto_now=True, help_text='Date and time of last modification to record', verbose_name='RecordModified')),
                ('q_code', models.CharField(help_text='Unique identifier for the qualification', max_length=36, primary_key=True, serialize=False, verbose_name='QCode')),
                ('date_issued', models.DateField(blank=True, help_text='Date when the qualification was issued', null=True, verbose_name='DateIssued')),
                ('date_valid', models.DateField(blank=True, help_text='Date until which the qualification is valid', null=True, verbose_name='DateValid')),
                ('minimum_period', models.IntegerField(default=90, help_text='Minimum period in days for the qualification', verbose_name='MinimumPeriod')),
                ('minimum_qty', models.IntegerField(default=3, help_text='Minimum quantity required for the qualification', verbose_name='MinimumQty')),
                ('notify_comment', models.TextField(blank=True, help_text='Comments for notification purposes', verbose_name='NotifyComment')),
                ('notify_days', models.IntegerField(default=14, help_text='Number of days before expiration to send notification', verbose_name='NotifyDays')),
                ('q_type_code', models.IntegerField(default=3, help_text='Code representing the type of qualification', verbose_name='QTypeCode')),
                ('ref_airfield', models.CharField(default='00000000-0000-0000-0000-000000000000', help_text='Reference to an airfield related to the qualification', max_length=36, verbose_name='RefAirfield')),
                ('ref_extra', models.IntegerField(default=0, help_text='Extra reference information for the qualification', verbose_name='RefExtra')),
                ('ref_model', models.CharField(default='G500', help_text='Reference to a model related to the qualification', max_length=255, verbose_name='RefModel')),
                ('validity', models.IntegerField(default=0, help_text='Validity status of the qualification', verbose_name='Validity')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
            },
        ),
    ]
